name: CI/CD
on:
  push:
    branches: [master, development]
    tags:
      - v[0-9]+.[0-9]+.[0-9]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          make install
      - name: Format code
        run: |
          make format
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          make install
      - name: Check formatting
        run: |
          - make checkFormat
      - name: Lint with pylint
        run: |
          make lint
      - name: Run tests
        run: |
          make test